apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-jaeger-datasource
  namespace: ${prometheus_namespace}
  labels:
    grafana_datasource: "true"
data:
  jaeger-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://jaeger-query.${namespace}.svc.cluster.local:80/jaeger
      isDefault: false
      jsonData:
        nodeGraph:
          enabled: true
        tracesToLogsV2:
          datasourceUid: 'loki'
        tracesToMetrics:
          datasourceUid: 'prometheus'
          tags: [{ key: 'service.name', value: 'service' }, { key: 'span.name', value: 'operation' }]
          queries:
            - name: 'Requisições por segundo'
              query: 'sum(rate(http_server_requests_seconds_count{service=\"$service\", span=\"$span\"}[$__rate_interval]))'
      uid: jaeger
      version: 1
      editable: true 